### ISSUE TITLE
Steer to mouse position

### ISSUE THREAD

**Issue by rexim** [tsoding/boids#31]
### Pieces

- [x] #39 Implement ViewPort dragging with mouse
- [x] #44 Take zoom factor into account while dragging the view
- [x] #40 Implement Boids following the cursor rule
